copyfile(fullfile(matlabroot,...
         'help','includes','product',...
         'images','global','ico_large_info.png'));

     [cdata] = imread('ico_large_info.png');

h=msgbox('Operation Completed',...
         'Success','custom',cdata);