function  y=Demodulate_Decode(u)
%#codegen
persistent  hDeModulator  hViterbi
if isempty(hDeModulator)
    %  System objects
    hDeModulator = comm.PSKDemodulator('ModulationOrder',4, ...
        'PhaseOffset',pi/4, ...
        'BitOutput',true, ...
        'DecisionMethod','Hard decision');
    hViterbi=comm.ViterbiDecoder(...
        'InputFormat','Hard',...
        'OutputDataType', 'logical',...
        'TerminationMethod','Terminated');
end
uB = step(hDeModulator, u);                                           % QPSK Demodulator
y = step(hViterbi,int8(uB));                                                % Viterbi Decoder
 