function y = MIMO_ChannelM(u)
%#codegen
Ts = (25/(3e6))*(378/864);
pathDelays=[0 0.4 0.9]*1e-6;
pathGains=[0 -5 -10];
maxDoppler=5;
persistent myChanObj
if isempty(myChanObj)
    myChanObj=comm.MIMOChannel(...
        'SampleRate', 1/Ts,...
        'PathDelays',pathDelays,...
        'AveragePathGains', pathGains,...
        'MaximumDopplerShift', maxDoppler,...
        'FadingDistribution','Rayleigh',...
        'NumTransmitAntennas',2,...
        'NumReceiveAntennas',1,...
        'ReceiveCorrelationMatrix',cat(3,1,1,1),...
        'RandomStream', 'mt19937ar with seed',...
        'Seed', 100,...
        'NormalizeChannelOutputs',false);
end
y = step(myChanObj, u);                                  % MIMO Channel Model
