function y = RayleighMPF14(chanIn)
%#codegen
Ts = (25/(3e6))*(186/576);
pathDelays=[0 0.4 0.9]*1e-6;
pathGains=[0 -5 -10];
maxDoppler=5;
persistent myChanObj
if isempty(myChanObj)
    myChanObj=comm.MIMOChannel(...
        'SampleRate', 1/Ts,...
        'PathDelays',pathDelays,...
        'AveragePathGains', pathGains,...
        'MaximumDopplerShift', maxDoppler,...
        'FadingDistribution','Rayleigh',...
        'NumTransmitAntennas',1,...
        'NumReceiveAntennas',1,...
        'TransmitCorrelationMatrix',1,...
        'NormalizeChannelOutputs',false,...
        'ReceiveCorrelationMatrix',1);
end
y = step(myChanObj, chanIn);